# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#-------------------------------------------Ventana principal

from PyQt5 import QtCore, QtGui, QtWidgets
from datamngmt import *
from addm import *
from reportint import *
import os

import time as tm
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # se crean todos los elementos de la ventana
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("font: 11pt \"Tw Cen MT\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(800, 600))
        self.frame.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_panel = QtWidgets.QFrame(self.frame)
        self.left_panel.setMinimumSize(QtCore.QSize(70, 600))
        self.left_panel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.left_panel.setStyleSheet("")
        self.left_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_panel.setObjectName("left_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_panel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.left_panel)
        self.frame_4.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout.addWidget(self.frame_4)
        self.left_side_menu = QtWidgets.QFrame(self.left_panel)
        self.left_side_menu.setMinimumSize(QtCore.QSize(70, 225))
        self.left_side_menu.setMaximumSize(QtCore.QSize(150, 225))
        self.left_side_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_dots = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_dots.setMinimumSize(QtCore.QSize(70, 15))
        self.btn_dots.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_dots.setAutoFillBackground(False)
        self.btn_dots.setStyleSheet("QPushButton{\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(16, 20, 23);\n"
"}")
        icon = QtGui.QIcon.fromTheme("settings")
        self.btn_dots.setIcon(icon)
        self.btn_dots.setIconSize(QtCore.QSize(70, 15))
        self.btn_dots.setFlat(True)
        self.btn_dots.setObjectName("btn_dots")
        self.verticalLayout_2.addWidget(self.btn_dots)
        self.btn_search = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_search.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_search.setStyleSheet("QPushButton{\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(187, 211, 253);\n"
"}")
        self.btn_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/dataicn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon)
        self.btn_search.setIconSize(QtCore.QSize(70, 70))
        self.btn_search.setFlat(True)
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout_2.addWidget(self.btn_search)
        self.btn_addpatient = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_addpatient.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_addpatient.setStyleSheet("QPushButton{\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(187, 211, 253);\n"
"}")
        self.btn_addpatient.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/addpicn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_addpatient.setIcon(icon1)
        self.btn_addpatient.setIconSize(QtCore.QSize(70, 70))
        self.btn_addpatient.setFlat(True)
        self.btn_addpatient.setObjectName("btn_addpatient")
        self.verticalLayout_2.addWidget(self.btn_addpatient)
        self.btn_analyze = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_analyze.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_analyze.setStyleSheet("QPushButton{\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(187, 211, 253);\n"
"}")
        self.btn_analyze.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/anicn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_analyze.setIcon(icon2)
        self.btn_analyze.setIconSize(QtCore.QSize(70, 70))
        self.btn_analyze.setFlat(True)
        self.btn_analyze.setObjectName("btn_analyze")
        self.verticalLayout_2.addWidget(self.btn_analyze)
        self.verticalLayout.addWidget(self.left_side_menu)
        self.frame_2 = QtWidgets.QFrame(self.left_panel)
        self.frame_2.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.left_panel)
        self.center_items = QtWidgets.QFrame(self.frame)
        self.center_items.setMinimumSize(QtCore.QSize(470, 600))
        self.center_items.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.center_items.setFrameShadow(QtWidgets.QFrame.Plain)
        self.center_items.setObjectName("center_items")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.center_items)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frm_center = QtWidgets.QFrame(self.center_items)
        self.frm_center.setStyleSheet("")
        self.frm_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_center.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_center.setObjectName("frm_center")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frm_center)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frm_center)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_patients = QtWidgets.QWidget()
        self.pg_patients.setStyleSheet("")
        self.pg_patients.setObjectName("pg_patients")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.pg_patients)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frm_pgdata = QtWidgets.QFrame(self.pg_patients)
        self.frm_pgdata.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_pgdata.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_pgdata.setObjectName("frm_pgdata")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frm_pgdata)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_searchbar = QtWidgets.QFrame(self.frm_pgdata)
        self.frame_searchbar.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_searchbar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_searchbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_searchbar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_searchbar.setObjectName("frame_searchbar")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_searchbar)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.frame_searchbar)
        self.frame_5.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.label = QtWidgets.QLabel(self.frame_searchbar)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setStyleSheet("color: rgb(16, 20, 23);")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.lineEdit_search = QtWidgets.QLineEdit(self.frame_searchbar)
        self.lineEdit_search.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(16, 20, 23);")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout_6.addWidget(self.lineEdit_search)
        self.frm_searchbarbtn = QtWidgets.QFrame(self.frame_searchbar)
        self.frm_searchbarbtn.setMinimumSize(QtCore.QSize(30, 10))
        self.frm_searchbarbtn.setMaximumSize(QtCore.QSize(10, 23))
        self.frm_searchbarbtn.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.frm_searchbarbtn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_searchbarbtn.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_searchbarbtn.setObjectName("frm_searchbarbtn")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frm_searchbarbtn)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_searchbar = QtWidgets.QPushButton(self.frm_searchbarbtn)
        self.btn_searchbar.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_searchbar.setStyleSheet("QPushButton{\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(187, 211, 253);\n"
"}")
        icon = QtGui.QIcon.fromTheme("s")
        self.btn_searchbar.setIcon(icon)
        self.btn_searchbar.setIconSize(QtCore.QSize(20, 20))
        self.btn_searchbar.setFlat(True)
        self.btn_searchbar.setObjectName("btn_searchbar")
        self.verticalLayout_8.addWidget(self.btn_searchbar)
        self.horizontalLayout_6.addWidget(self.frm_searchbarbtn)
        self.frame_7 = QtWidgets.QFrame(self.frame_searchbar)
        self.frame_7.setMinimumSize(QtCore.QSize(40, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6.addWidget(self.frame_7)
        self.verticalLayout_7.addWidget(self.frame_searchbar)
        self.frm_listpatients = QtWidgets.QFrame(self.frm_pgdata)
        self.frm_listpatients.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_listpatients.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_listpatients.setObjectName("frm_listpatients")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frm_listpatients)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tbl_patients = QtWidgets.QTableWidget(self.frm_listpatients)
        self.tbl_patients.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tbl_patients.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tbl_patients.setColumnCount(8)
        self.tbl_patients.setHorizontalHeaderLabels(['ID','Nombre','Edad','Sexo','Antecedentes','Peso(kg)','Estatura(m)','Escolaridad'])
        self.tbl_patients.horizontalHeaderItem(0).setTextAlignment(4)
        self.tbl_patients.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tbl_patients.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_patients.setObjectName("tbl_patients")
        self.verticalLayout_9.addWidget(self.tbl_patients)
        self.verticalLayout_7.addWidget(self.frm_listpatients)
        self.horizontalLayout_5.addWidget(self.frm_pgdata)
        self.stackedWidget.addWidget(self.pg_patients)
        self.pg_addpatient = QtWidgets.QWidget()
        self.pg_addpatient.setStyleSheet("")
        self.pg_addpatient.setObjectName("pg_addpatient")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pg_addpatient)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frm_pgaddpatient = QtWidgets.QFrame(self.pg_addpatient)
        self.frm_pgaddpatient.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_pgaddpatient.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_pgaddpatient.setObjectName("frm_pgaddpatient")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frm_pgaddpatient)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_12 = QtWidgets.QFrame(self.frm_pgaddpatient)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_12.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_12)
        self.label_2.setMinimumSize(QtCore.QSize(70, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_7.addWidget(self.lineEdit_name)
        self.label_3 = QtWidgets.QLabel(self.frame_12)
        self.label_3.setMinimumSize(QtCore.QSize(150, 25))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.fecha_nacimiento = QtWidgets.QDateEdit(self.frame_12)
        self.fecha_nacimiento.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fecha_nacimiento.setObjectName("fecha_nacimiento")
        self.horizontalLayout_7.addWidget(self.fecha_nacimiento)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_7.addWidget(self.frame_13)
        self.verticalLayout_10.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.frm_pgaddpatient)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_11.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setMinimumSize(QtCore.QSize(30, 25))
        self.label_11.setMaximumSize(QtCore.QSize(20, 25))
        self.label_11.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.lineEdit_ID = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_ID.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.horizontalLayout_8.addWidget(self.lineEdit_ID)
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        self.label_4.setMinimumSize(QtCore.QSize(70, 25))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.box_sexo = QtWidgets.QComboBox(self.frame_11)
        self.box_sexo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.box_sexo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.box_sexo.setDuplicatesEnabled(False)
        self.box_sexo.setFrame(True)
        self.box_sexo.setObjectName("box_sexo")
        self.box_sexo.addItem("")
        self.box_sexo.addItem("")
        self.box_sexo.addItem("")
        self.horizontalLayout_8.addWidget(self.box_sexo)
        self.label_5 = QtWidgets.QLabel(self.frame_11)
        self.label_5.setMinimumSize(QtCore.QSize(70, 25))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.spin_peso = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.spin_peso.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_peso.setFrame(True)
        self.spin_peso.setMaximum(200.0)
        self.spin_peso.setSingleStep(0.1)
        self.spin_peso.setObjectName("spin_peso")
        self.horizontalLayout_8.addWidget(self.spin_peso)
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setMinimumSize(QtCore.QSize(85, 25))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_6.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.spin_estatura = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.spin_estatura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_estatura.setFrame(True)
        self.spin_estatura.setMaximum(200.0)
        self.spin_estatura.setSingleStep(0.1)
        self.spin_estatura.setObjectName("spin_estatura")
        self.horizontalLayout_8.addWidget(self.spin_estatura)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.frm_pgaddpatient)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setMinimumSize(QtCore.QSize(100, 25))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_7.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.lineEdit_escolaridad = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_escolaridad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_escolaridad.setObjectName("lineEdit_escolaridad")
        self.horizontalLayout_9.addWidget(self.lineEdit_escolaridad)
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        self.label_8.setMinimumSize(QtCore.QSize(100, 25))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_8.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEdit_antecedentes = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_antecedentes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_antecedentes.setObjectName("lineEdit_antecedentes")
        self.horizontalLayout_9.addWidget(self.lineEdit_antecedentes)
        self.verticalLayout_10.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frm_pgaddpatient)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setContentsMargins(0, 9, 0, 9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setMinimumSize(QtCore.QSize(100, 25))
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.txtEdit_semiologia = QtWidgets.QPlainTextEdit(self.frame_9)
        self.txtEdit_semiologia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtEdit_semiologia.setObjectName("txtEdit_semiologia")
        self.horizontalLayout_10.addWidget(self.txtEdit_semiologia)
        self.verticalLayout_10.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frm_pgaddpatient)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setMinimumSize(QtCore.QSize(100, 25))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setStyleSheet("background-color: rgba(22, 185, 194, 75);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.txtEdit_historiaclinica = QtWidgets.QPlainTextEdit(self.frame_8)
        self.txtEdit_historiaclinica.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtEdit_historiaclinica.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtEdit_historiaclinica.setObjectName("txtEdit_historiaclinica")
        self.horizontalLayout_11.addWidget(self.txtEdit_historiaclinica)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.frame_buttons = QtWidgets.QFrame(self.frm_pgaddpatient)
        self.frame_buttons.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_buttons)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_14 = QtWidgets.QFrame(self.frame_buttons)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_12.addWidget(self.frame_14)
        self.btn_descartarpatient = QtWidgets.QPushButton(self.frame_buttons)
        self.btn_descartarpatient.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_descartarpatient.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_descartarpatient.setAutoFillBackground(False)
        self.btn_descartarpatient.setStyleSheet("QPushButton{\n"
"    background-color: rgb(167, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 61, 61);\n"
"}")
        self.btn_descartarpatient.setFlat(True)
        self.btn_descartarpatient.setObjectName("btn_descartarpatient")
        self.btn_descartarpatient.setText("Descartar")
        self.horizontalLayout_12.addWidget(self.btn_descartarpatient)
        self.btn_guardarpatient = QtWidgets.QPushButton(self.frame_buttons)
        self.btn_guardarpatient.setMinimumSize(QtCore.QSize(0, 21))
        self.btn_guardarpatient.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_guardarpatient.setAutoFillBackground(False)
        self.btn_guardarpatient.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 167, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(61, 230, 180);\n"
"}")
        self.btn_guardarpatient.setFlat(True)
        self.btn_guardarpatient.setObjectName("btn_guardarpatient")
        self.btn_guardarpatient.setText("Guardar")
        self.horizontalLayout_12.addWidget(self.btn_guardarpatient)
        self.verticalLayout_10.addWidget(self.frame_buttons)
        self.verticalLayout_6.addWidget(self.frm_pgaddpatient)
        self.stackedWidget.addWidget(self.pg_addpatient)
        self.pg_analyze = QtWidgets.QWidget()
        self.pg_analyze.setStyleSheet("")
        self.pg_analyze.setObjectName("pg_analyze")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pg_analyze)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frm_pganalyze = QtWidgets.QFrame(self.pg_analyze)
        self.frm_pganalyze.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_pganalyze.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_pganalyze.setObjectName("frm_pganalyze")
        self.verticalLayout_5.addWidget(self.frm_pganalyze)
        self.stackedWidget.addWidget(self.pg_analyze)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frm_center)
        self.horizontalLayout.addWidget(self.center_items)
        self.right_panel = QtWidgets.QFrame(self.frame)
        self.right_panel.setMinimumSize(QtCore.QSize(70, 600))
        self.right_panel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.right_panel.setStyleSheet("")
        self.right_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_panel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_panel.setObjectName("right_panel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_panel)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.right_panel)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3.addWidget(self.frame_6)
        self.right_side_menu = QtWidgets.QFrame(self.right_panel)
        self.right_side_menu.setMinimumSize(QtCore.QSize(70, 210))
        self.right_side_menu.setMaximumSize(QtCore.QSize(150, 210))
        self.right_side_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_side_menu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_side_menu.setObjectName("right_side_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_side_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_record = QtWidgets.QPushButton(self.right_side_menu)
        self.btn_record.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_record.setStyleSheet("QPushButton{\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(160,240,170);\n"
"}")
        self.btn_record.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/addmicn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_record.setIcon(icon3)
        self.btn_record.setIconSize(QtCore.QSize(70, 70))
        self.btn_record.setFlat(True)
        self.btn_record.setObjectName("btn_record")
        self.verticalLayout_4.addWidget(self.btn_record)
        self.btn_report = QtWidgets.QPushButton(self.right_side_menu)
        self.btn_report.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_report.setStyleSheet("QPushButton{\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(160,240,170);\n"
"}")
        self.btn_report.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/repicn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_report.setIcon(icon4)
        self.btn_report.setIconSize(QtCore.QSize(70, 70))
        self.btn_report.setFlat(True)
        self.btn_report.setObjectName("btn_report")
        self.verticalLayout_4.addWidget(self.btn_report)

        self.btn_del = QtWidgets.QPushButton(self.right_side_menu)
        self.btn_del.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_del.setStyleSheet("QPushButton{\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(209, 161, 184);\n"
"}")
        self.btn_del.setText("")
        icon3del = QtGui.QIcon()
        icon3del.addPixmap(QtGui.QPixmap("icons/dellpat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del.setIcon(icon3del)
        self.btn_del.setIconSize(QtCore.QSize(70, 70))
        self.btn_del.setFlat(True)
        self.btn_del.setObjectName("btn_record")
        self.verticalLayout_4.addWidget(self.btn_del)

        self.verticalLayout_3.addWidget(self.right_side_menu)
        self.frame_3 = QtWidgets.QFrame(self.right_panel)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.right_panel)
        self.horizontalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        #se establecen las funciones de cada botón
        self.btn_dots.clicked.connect(lambda: self.slideleftmenu())
        self.btn_search.clicked.connect(lambda: self.showpgdata())
        self.btn_addpatient.clicked.connect(lambda: self.showpgadpatient())
        self.btn_analyze.clicked.connect(lambda: self.showanalyze())
        self.btn_guardarpatient.clicked.connect(lambda: self.savepatient())
        self.btn_descartarpatient.clicked.connect(lambda: self.discardpatient())
        self.btn_record.clicked.connect(lambda:self.addmeasure())
        self.btn_report.clicked.connect(lambda:self.show_report())
        self.btn_del.clicked.connect(lambda:self.dellpatient())
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.updatetable()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def dellpatient(self):
        #se borra el archivo de un paciente
        a = self.tbl_patients.selectedIndexes()
        rows = [k.row() for k in a]
        if a==[]:
            #no se ha seleccionado ninguno en la tabla
            showdialog([196,88],icon="⚠️",msg="Seleccione un paciente")
        else:
            if (len(rows)==rows.count(rows[0])):
                idn = self.tbl_patients.item(rows[0],0).text()
                l1 = len(os.listdir('data'))
                remove_pat(idn)
                l2 = len(os.listdir('data'))
                if l2<l1:
                    showdialog([196,88],icon="✔️",msg="Paciente con ID:"+idn+"eliminado")
                    self.updatetable()
            else:
                # hay varios pacientes seleccionados en la tabla
                showdialog([196,88],icon="⚠️",msg="Seleccione sólo un paciente")


    def discardpatient(self):
        #se borra los campos de agregar paciente
        self.stackedWidget.setCurrentIndex(0)
        self.updatetable()
        self.lineEdit_ID.setText("")
        self.lineEdit_name.setText("")
        self.lineEdit_antecedentes.setText("")
        self.lineEdit_escolaridad.setText("")
        self.box_sexo.setCurrentIndex(0)
        self.spin_peso.setValue(0.00)
        self.spin_estatura.setValue(0.00)
        self.txtEdit_semiologia.setPlainText("")
        self.txtEdit_historiaclinica.setPlainText("")
        self.fecha_nacimiento.setDate(date(2000,1,1))

    def savepatient(self):
        # se crea un archivo para un nuevo paciente
        filenames = [k.split('.')[0] for k in os.listdir('data')]
        if self.lineEdit_ID.text()=="":
            # si el ID está vacío
            showdialog([283, 82],icon="⚠️",msg="El campo \"ID\" se encuentra vacío",toast=False)
            del filenames
        elif self.lineEdit_ID.text() in filenames:
            # si ya existe un paciente con el ID
            showdialog([283, 82],icon="⚠️",msg="El \"ID\""+self.lineEdit_ID.text()+"ya existe",toast=False)
            del filenames
        else:
            # se guarda el archivo
            pat = [self.lineEdit_ID.text(),self.lineEdit_name.text(),self.fecha_nacimiento.text(),self.box_sexo.currentText(),float(self.spin_peso.text().replace(',','.')),float(self.spin_estatura.text().replace(',','.')),self.lineEdit_escolaridad.text(),self.lineEdit_antecedentes.text(),self.txtEdit_semiologia.toPlainText(),self.txtEdit_historiaclinica.toPlainText()]
            pat2 = [k if (k!=0.0 and k!='Seleccionar...') else '' for k in pat]
            saved = adduser(pat2[0],pat2[1],pat2[2],pat2[3],pat2[4],pat2[5],pat2[6],pat2[7],pat2[8],pat2[9])
            print('saved',saved)
            if saved:
                showdialog([166, 64],icon="✔️",msg="Paciente guardado",toast=True)    
                #print(data)
                self.updatetable()
                ###aca quede!!!!!!!
                self.lineEdit_ID.setText("")
                self.lineEdit_name.setText("")
                self.lineEdit_antecedentes.setText("")
                self.lineEdit_escolaridad.setText("")
                self.box_sexo.setCurrentIndex(0)
                self.spin_peso.setValue(0.00)
                self.spin_estatura.setValue(0.00)
                self.txtEdit_semiologia.setPlainText("")
                self.txtEdit_historiaclinica.setPlainText("")
                self.fecha_nacimiento.setDate(date(2000,1,1))

    def updatetable(self):
        #se actualiza la tabla de pacientes
        #filenames = os.listdir('data')
        tbl1 = open_table()
        self.tbl_patients.setRowCount(len(tbl1))
        [self.tbl_patients.setItem(i,j,QtWidgets.QTableWidgetItem(str(tbl1[i][j]))) for i in range(0,len(tbl1)) for j in range(0,len(tbl1[i]))] 
        self.tbl_patients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

    def show_report(self):
        #ver el reporte de un paciente
        a = self.tbl_patients.selectedIndexes()
        rows = [k.row() for k in a]
        if a==[]:
            #no hay ninguno seleccionado
            showdialog([196,88],icon="⚠️",msg="Seleccione un paciente")
        else:
            if (len(rows)==rows.count(rows[0])):
                #se abre la ventana de reporte
                idn = self.tbl_patients.item(rows[0],0).text()
                self.windowreport(idn)
            else:
                #hay varios seleccionados
                showdialog([196,88],icon="⚠️",msg="Seleccione sólo un paciente")
    
    def windowreport(self, idn):
        #se crea y abre la ventana de reporte (reportint.py)
        wind = QtWidgets.QDialog()
        wind.setWindowFlag(QtCore.Qt.WindowMinimizeButtonHint,True)
        wind.setWindowFlag(QtCore.Qt.WindowMaximizeButtonHint,True)
        ui = Ui_Report()
        ui.setupUi(wind, idn=idn)
        wind.exec()

    def showpgdata(self):
        #se muestra la tabla de pacientes y se borran los campos de agregar paciente
        self.stackedWidget.setCurrentIndex(0)
        self.updatetable()
        self.lineEdit_ID.setText("")
        self.lineEdit_name.setText("")
        self.lineEdit_antecedentes.setText("")
        self.lineEdit_escolaridad.setText("")
        self.box_sexo.setCurrentIndex(0)
        self.spin_peso.setValue(0.00)
        self.spin_estatura.setValue(0.00)
        self.txtEdit_semiologia.setPlainText("")
        self.txtEdit_historiaclinica.setPlainText("")
        self.fecha_nacimiento.setDate(date(2000,1,1))
    def showpgadpatient(self):
        #se muestra la parte para agregar un paciente
        self.stackedWidget.setCurrentIndex(1)
    def showanalyze(self):
        #Se muestra la parte para hacer análisis de datos
        #Desarrollar una nueva ventana para esto
        self.stackedWidget.setCurrentIndex(2)

    def addmeasure(self):
        #se adiciona una medida sobre el paciente
        a = self.tbl_patients.selectedIndexes()
        rows = [k.row() for k in a]
        if a==[]:
            #no hay paciente seleccionado
            showdialog([196,88],icon="⚠️",msg="Seleccione un paciente")
        else:
            if (len(rows)==rows.count(rows[0])):
                #se abre la ventana de nueva medida
                idn = self.tbl_patients.item(rows[0],0).text()
                self.windowacq(idn)
            else:
                #hay varios pacientes seleccionados
                showdialog([196,88],icon="⚠️",msg="Seleccione sólo un paciente")
    
    def windowacq(self,idn):
        #se crea y abre la ventana de adicionar una medida sobre el paciente
        wind = QtWidgets.QDialog()
        wind.setWindowFlag(QtCore.Qt.WindowMinimizeButtonHint,True)
        wind.setWindowFlag(QtCore.Qt.WindowMaximizeButtonHint,True)
        ui = Ui_Addmeasure()
        ui.setupUi(wind, idn=idn)
        wind.exec()

    def slideleftmenu(self):
        #se muestra la descripción de los botones
        width = self.left_side_menu.width()
        if width == 70:
            self.animation = QtCore.QPropertyAnimation(self.left_panel,b"minimumWidth")
            self.animation.setDuration(100)
            self.animation.setStartValue(width)
            self.animation.setEndValue(170)
            self.animation2 = QtCore.QPropertyAnimation(self.right_panel,b"minimumWidth")
            self.animation2.setDuration(100)
            self.animation2.setStartValue(width)
            self.animation2.setEndValue(150)
            self.animation3 = QtCore.QPropertyAnimation(self.right_side_menu,b"minimumWidth")
            self.animation3.setDuration(100)
            self.animation3.setStartValue(width)
            self.animation3.setEndValue(150) 
            self.animation.start()
            self.animation2.start()
            self.animation3.start()
            self.btn_search.setText("Buscar")
            self.btn_analyze.setText("Analizar \n datos")
            self.btn_addpatient.setText("Agregar \n paciente")
            self.btn_record.setText("Nueva \n medida")
            self.btn_report.setText("Reporte")
            self.btn_del.setText("Borrar \n paciente")
        else:
            self.animation = QtCore.QPropertyAnimation(self.left_panel,b"minimumWidth")
            self.animation.setDuration(100)
            self.animation.setStartValue(width)
            self.animation.setEndValue(70)
            self.animation2 = QtCore.QPropertyAnimation(self.right_panel,b"minimumWidth")
            self.animation2.setDuration(100)
            self.animation2.setStartValue(150)
            self.animation2.setEndValue(70)
            self.animation3 = QtCore.QPropertyAnimation(self.right_side_menu,b"minimumWidth")
            self.animation3.setDuration(150)
            self.animation3.setStartValue(width)
            self.animation3.setEndValue(70) 
            self.animation.start()
            self.animation2.start()
            self.animation3.start()
            self.btn_search.setText("")
            self.btn_analyze.setText("")
            self.btn_addpatient.setText("")
            self.btn_record.setText("")
            self.btn_report.setText("")
            self.btn_del.setText("")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dots.setText(_translate("MainWindow", "• • • "))
        self.label.setText(_translate("MainWindow", "Buscar:"))
        self.btn_searchbar.setText(_translate("MainWindow", "🔍"))
        self.label_2.setText(_translate("MainWindow", "Nombre :"))
        self.label_3.setText(_translate("MainWindow", "Fecha de Nacimiento :"))
        self.label_11.setText(_translate("MainWindow", "ID :"))
        self.label_4.setText(_translate("MainWindow", "Sexo :"))
        self.box_sexo.setItemText(0, _translate("MainWindow", "Seleccionar..."))
        self.box_sexo.setItemText(1, _translate("MainWindow", "Masculino"))
        self.box_sexo.setItemText(2, _translate("MainWindow", "Femenino"))
        self.label_5.setText(_translate("MainWindow", "Peso (kg) :"))
        self.label_6.setText(_translate("MainWindow", "Estatura (m) :"))
        self.label_7.setText(_translate("MainWindow", "Escolaridad :"))
        self.label_8.setText(_translate("MainWindow", "Antecedentes :"))
        self.label_9.setText(_translate("MainWindow", "Semiología"))
        self.label_10.setText(_translate("MainWindow", "Historia \n"
" Clínica"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ret = app.exec_()
    #savedata()
    sys.exit(ret)
